services:
  docker-jokes:
    image: taniotoshi/docker-jokes:dev
    container_name: docker-jokes
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.28.0-alpine3.21}
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - .env.local
    ports:
      - '8080:8080'
