services:
  docker-jokes:
    image: taniotoshi/docker-jokes:dev
    container_name: docker-jokes
    build:
      context: src
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - .env.local
    ports:
      - '8080:8080'
